/**
 * Catalogue source adapter.
 *
 * Default: the snapshot committed under src/data/, generated by
 * `npm run sync-data`. The app ships with data, needs no key, and works offline.
 *
 * Live mode: set VITE_LIVE_GQL_ENDPOINT + VITE_LIVE_GQL_KEY to fetch from the
 * GraphQL API at runtime instead. Note the API's CORS allowlist must include
 * your origin; as of writing it only admits https://avakot.market.
 *
 * Both paths return the same normalized shape, so nothing downstream cares.
 */

import temperData from '../data/tempers.json'
import weaponData from '../data/weapons.json'
import metaData from '../data/meta.json'

const LIVE_ENDPOINT = import.meta.env?.VITE_LIVE_GQL_ENDPOINT
const LIVE_KEY = import.meta.env?.VITE_LIVE_GQL_KEY

const LIVE_QUERY = `
  query Catalogue {
    tempers { ItemID Icon Description Name Stats TemperType possibleWeapons { name } subcategory faction }
    weapons { ItemID Description Slot Rarity Art Origin ImgIcon possibleTempers }
  }
`

/** Index a normalized catalogue for O(1) lookups. */
function index(tempers, weapons, meta) {
  return {
    tempers,
    weapons,
    meta,
    temperById: new Map(tempers.map((t) => [t.id, t])),
    weaponById: new Map(weapons.map((w) => [w.id, w])),
  }
}

export async function loadCatalogue() {
  if (LIVE_ENDPOINT && LIVE_KEY) {
    try {
      return await loadLive()
    } catch (err) {
      // A live failure should degrade to the snapshot, not to a blank page.
      console.warn('[catalogue] live fetch failed, falling back to bundled snapshot:', err)
    }
  }
  return index(temperData, weaponData, metaData)
}

async function loadLive() {
  const res = await fetch(LIVE_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-API-Key': LIVE_KEY },
    body: JSON.stringify({ query: LIVE_QUERY }),
  })
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  const json = await res.json()
  if (json.errors?.length) throw new Error(json.errors[0].message)

  // `normalize` is shared with the sync script so live and snapshot agree.
  const { normalizeTemper, normalizeWeapon, isPlaceholder } = await import('./normalize.js')
  const tempers = (json.data.tempers ?? []).map(normalizeTemper).filter((t) => !isPlaceholder(t)).sort(byName)
  const weapons = (json.data.weapons ?? []).map(normalizeWeapon).filter((w) => !isPlaceholder(w)).sort(byName)

  return index(tempers, weapons, {
    source: 'live',
    syncedAt: new Date().toISOString(),
    counts: { tempers: tempers.length, weapons: weapons.length },
  })
}

function byName(a, b) {
  return a.name.localeCompare(b.name)
}

/**
 * Resolve an icon to a URL.
 *
 * Sync writes compressed WebP into public/icons/, which is what we prefer:
 * same-origin, ~5KB each, and service-worker cacheable. If a snapshot predates
 * the icon download we fall back to the public (uncompressed, 512px) API host.
 */
const ICON_FALLBACK = 'https://api.avakot.org/v1/I'

export function iconUrl(file, { local = true } = {}) {
  if (!file) return null
  const base = import.meta.env?.BASE_URL ?? '/'
  if (local) return `${base}icons/${file.replace(/\.(png|jpe?g|webp)$/i, '')}.webp`
  return `${ICON_FALLBACK}/${file}`
}

export function remoteIconUrl(file) {
  return file ? `${ICON_FALLBACK}/${file}` : null
}
